# example config file for using lapwing dictionaries

[dictionary]
path = "dictionaries/"
dictionaries = [
    "lapwing-commands.json",
    "lapwing-numbers.json",
    "lapwing-uk-additions.json",
    "lapwing-proper-nouns.json",
    "lapwing-base.json",
]

[keyboard]
path = "/dev/input/event12"

[machine]
arpeggiate = true
